title: Alexander Chai
logo: /asset/AlexPicture.png

description: Commerce student at Smith School of Business, Queen's University, specializing in Finance. 

# author: linkedin

show_downloads: true
theme: jekyll-theme-minimal
