title: Alexander Chai
logo: /asset/AlexPicture.png

description: Commerce student at Smith School of Business, Queen's University, specializing in Finance. Seeking co-op opportunities in valuation, financial modelling, and investment analysis. 

# author: linkedin

show_downloads: true
theme: jekyll-theme-minimal
